dist: bionic

language: minimal

env:
  global:
    - REPO=docksal/mariadb

  matrix:
    - VERSION=5.5 FROM=mariadb:5.5
    - VERSION=10.0 FROM=mariadb:10.0
    - VERSION=10.1 FROM=mariadb:10.1
    - VERSION=10.2 FROM=mariadb:10.2
    - VERSION=10.3 FROM=mariadb:10.3

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - make
  - make test

after_success:
  - make release

after_failure:
  - make logs
